BulkyBook.Web/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.Common.Interfaces;
using BulkyBook.Common.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;
using static BulkyBook.Common.Constants;

namespace BulkyBook.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = $"{nameof(Roles.SuperAdmin)},{nameof(Roles.Admin)}")]
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }


        public IActionResult Index()
        {
            IEnumerable<Company> companies = _unitOfWork.CompanyRepository.GetAll();
            return View(companies);
        }

        public IActionResult CreateEdit(int? id)
        {
            //Add
            if (id == null)
            {
                var company = new Company();
                return View(company);
            }
            else
            {
                var company = _unitOfWork.CompanyRepository.Find(id);
                if (company == null)
                {
                    TempData["Error"] = $"No Company found with id={id}";
                }
                else
                {
                    return View(company);
                }
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = $"Invalid id {id}.";
            }
            else
            {
                var company = _unitOfWork.CompanyRepository.Find(id);
                if (company == null)
                {
                    TempData["Error"] = $"Invalid id {id}.";
                }
                else
                {
                    _unitOfWork.CompanyRepository.Delete(company);
                    _unitOfWork.SaveChanges();
                    TempData["Success"] = $"Deleted {id} successfully.";
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddUpdate(Company company)
        {
            var success = true;
            if (company.Id == 0)
            {
                if (ModelState.IsValid)
                {
                    var existingCompany = _unitOfWork.CompanyRepository.GetByExpression(e => e.Name == company.Name);
                    if (existingCompany != null)
                    {
                        TempData["Error"] = $"Company {company.Name} already exists.";
                        success = false;
                    }
                    else
                    {
                        var isValid = this.IsCompanyNameValid(company);
                        if (isValid)
                        {
                            this._unitOfWork.CompanyRepository.Insert(company);
                            this._unitOfWork.SaveChanges();
                            TempData["Success"] = $"Company {company.Name} created successfully.";
                        }
                        else
                        {
                            ModelState.AddModelError(nameof(Category.Name), "Name is Invalid");
                            success = false;
                        }
                    }
                }
                else
                    success = false;
            }
            else
            {
                var isValid = this.IsCompanyNameValid(company);
                if (isValid)
                {
                    this._unitOfWork.CompanyRepository.Update(company);
                    this._unitOfWork.SaveChanges();
                    TempData["Success"] = $"Company {company.Name} updated successfully.";
                }
                else
                {
                    ModelState.AddModelError(nameof(Company.Name), "Name is Invalid");
                    success = false;
                }
            }
            if (success)
                return RedirectToAction(nameof(Index));
            else
                return View(nameof(CreateEdit), company);
        }

        private bool IsCompanyNameValid(Company company)
        {
            var regexMatch = Regex.Match(company.Name, @"([~|!])");
            return !regexMatch.Success;
        }
    }
}

BulkyBook.Web/Areas/Admin/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using static BulkyBook.Common.Constants;

namespace BulkyBook.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = nameof(Roles.SuperAdmin))]
    [Area("Admin")]
    public class RolesController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            this._roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        public IActionResult CreateEdit(string id)
        {
            //Add
            if (id == null)
            {
                return View(new IdentityRole());
            }
            else
            {
                var role = _roleManager.FindByIdAsync(id);
                if (role == null)
                {
                    TempData["Error"] = $"No cover found with id={id}.";
                }
                else
                {
                    return View(role);
                }
            }
            return View();
        }

    }
}

BulkyBook.Web/Areas/Admin/Controllers/UserController.cs
using BulkyBook.Common.Interfaces;
using BulkyBook.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using static BulkyBook.Common.Constants;

namespace BulkyBook.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = nameof(Roles.SuperAdmin))]
    [Area("Admin")]
    public class UserController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private UserManager<Common.Models.Customer> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<Common.Models.Customer> userManager, RoleManager<IdentityRole> roleManager, IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
            this._userManager = userManager;
            this._roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var nonLoggedInUsers = _userManager.Users.ToList();
            if (currentUser != null)
                nonLoggedInUsers = _userManager.Users.Where(e => e.Name != currentUser.Name).ToList();
            return View(nonLoggedInUsers);
        }

        public async Task<IActionResult> RoleList(string id)
        {
            var currentUser = await _userManager.FindByIdAsync(id);
            var currentUserRoles = await _userManager.GetRolesAsync(currentUser);
            var otherRoles = this._roleManager.Roles;

            var userRoleList = new List<UserRoleViewModel>();
            foreach (var role in currentUserRoles)
            {
                userRoleList.Add(new UserRoleViewModel
                {
                    IsAssigned = true,
                    RoleName = role

                });
            }
            foreach (var role in otherRoles)
            {
                if (!userRoleList.Any(e => e.RoleName == role.Name))
                {
                    userRoleList.Add(new UserRoleViewModel
                    {
                        IsAssigned = false,
                        RoleName = role.Name

                    });
                }
            }
            var manageUserRole = new ManageUserRoleViewModel()
            {
                UserRoleId = id,
                Roles = userRoleList
            };
            return View(manageUserRole);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateUserRole(ManageUserRoleViewModel manageUserRoleViewModel)
        {
            var user = await this._userManager.FindByIdAsync(manageUserRoleViewModel.UserRoleId);
            if (user != null)
            {
                var userRoles = await this._userManager.GetRolesAsync(user);
                await this._userManager.RemoveFromRolesAsync(user, userRoles);
                await this._userManager.AddToRolesAsync(user, manageUserRoleViewModel.Roles.Where(e => e.IsAssigned).Select(e => e.RoleName));
                TempData["Success"] = "Successfully updated roles.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["Error"] = "No user found.";
                return View(nameof(RoleList), manageUserRoleViewModel);
            }
        }
    }
}

BulkyBook.Web/Component/ShoppingCartViewComponent.cs
using BulkyBook.Common;
using BulkyBook.Common.Interfaces;
using BulkyBook.Common.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace BulkyBook.Web.Components
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private IUnitOfWork _unitOfWork;
        private UserManager<Customer> _userManager;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork, UserManager<Customer> userManager)
        {
            this._unitOfWork = unitOfWork;
            this._userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user != null)
            {
                if (!HttpContext.Session.Keys.Any(e => e == Constants.CartCount))
                {
                    var userCartCount = this._unitOfWork.ShoppingCartRepository.GetAll(e => e.UserId == user.Id).Count();
                    HttpContext.Session.SetInt32(Constants.CartCount, userCartCount);
                }
                var cartCount = HttpContext.Session.GetInt32(Constants.CartCount);
                return View(new Dummy() { CartCount = cartCount?.ToString() });
            }

            return View(new Dummy());
        }

    }

    public class Dummy
    {
        public string CartCount { get; set; } = "0";
    }
}

BulkyBook.Web/Views/Shared/_Layout.cshtml
@using BulkyBook.Common
@using static BulkyBook.Common.Constants
@using Microsoft.AspNetCore.Http

@inject UserManager<Customer> userManager;
@{
    var currentUser = await userManager.GetUserAsync(Context.User);
    var userRoles = currentUser != null ? await userManager.GetRolesAsync(currentUser) : null;
    var isAdminOrSuperAdmin = userRoles != null && (userRoles.Any(e => e == Roles.SuperAdmin.ToString())
    || userRoles.Any(e => e == Roles.Admin.ToString()));
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBook.Web</title>
    <link rel="stylesheet" href="~/css/bootsWatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBook.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Privacy">
                                Privacy
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>

                        @if (isAdminOrSuperAdmin)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                               aria-haspopup="true" aria-expanded="false">Admin Options</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Feature" asp-action="Index">Feature</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User Management</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Roles" asp-action="Index">Role Management</a>
                                </div>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="OrderManagement"
                               asp-action="Index">
                                Order Management
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>

                        <li class="nav-item align-content-end">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                Cart
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>

                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted footer">
        <div class="container">
            &copy; 2022 - BulkyBook.Web -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <partial name="_toaster" />
</body>
</html>

BulkyBook.Web/Views/Shared/_toaster.cshtml
<div hidden id="toaster" class="toast show" role="alert" 
aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <strong class="me-auto">Bootstrap</strong>
        <button type="button" class="btn-close ms-2 mb-1" 
        data-bs-dismiss="toast" aria-label="Close">
            <span aria-hidden="true"></span>
        </button>
    </div>
    <div class="toast-body">
        Hello, world! This is a toast message.
    </div>
</div>

@{
    //mytoaster is defined in site.js
    if (@TempData["Success"] != null)
    {
        <script type="text/javascript">
            mytoaster.displayToaster('Success','@TempData["Success"]');
        </script>
    }
    if (@TempData["Error"] != null)
    {
        <script type="text/javascript">
            mytoaster.displayToaster('Error','@TempData["Error"]');
        </script>
    }
}