BulkyBook.Web/Areas/Admin/Controllers/FeatureController.cs
using BulkyBook.Common.Interfaces;
using BulkyBook.Common.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace BulkyBook.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FeatureController : Controller
    {

        private IUnitOfWork _unitOfWork;

        public FeatureController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var feature = this._unitOfWork.FeatureRepository.GetAll();
            return View(feature);
        }

        public IActionResult CreateEdit(int? id)
        {
            //Add
            if (id == null)
            {
                return View(new Feature());
            }
            else
            {
                var coverType = _unitOfWork.FeatureRepository.Find(id);
                if (coverType == null)
                {
                    TempData["Error"] = $"No feature found with id={id}.";
                }
                else
                {
                    return View(coverType);
                }
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["Error"] = $"Invalid id {id}.";
            }
            else
            {
                var feature = _unitOfWork.FeatureRepository.Find(id);
                if (feature == null)
                {
                    TempData["Error"] = $"Invalid id {id}.";
                }
                else
                {
                    _unitOfWork.FeatureRepository.Delete(feature);
                    _unitOfWork.SaveChanges();
                    TempData["Success"] = $"Deleted {id} successfully.";
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddUpdate(Feature feature)
        {
            var success = true;
            if (feature.Id == 0)
            {
                if (ModelState.IsValid)
                {
                    var existingCoverType = _unitOfWork.FeatureRepository
                        .GetByExpression(e => e.ControllerName == feature.ControllerName);
                    if (existingCoverType != null)
                    {
                        TempData["Error"] = $"Feature {feature.ControllerName} already exists.";
                        success = false;
                    }
                    else
                    {
                        var isValid = this.IsFeatureNameValid(feature);
                        if (isValid)
                        {
                            this._unitOfWork.FeatureRepository.Insert(feature);
                            this._unitOfWork.SaveChanges();
                            TempData["Success"] = $"Feature {feature.ControllerName} created successfully.";
                        }
                        else
                        {
                            ModelState.AddModelError(nameof(Feature.ControllerName), "Name is Invalid");
                            success = false;
                        }
                    }
                }
                else
                    success = false;
            }
            else
            {
                var isValid = this.IsFeatureNameValid(feature);
                if (isValid)
                {
                    this._unitOfWork.FeatureRepository.Update(feature);
                    this._unitOfWork.SaveChanges();
                    TempData["Success"] = $"Feature {feature.ControllerName} updated successfully.";
                }
                else
                {
                    ModelState.AddModelError(nameof(Feature.ControllerName), "Name is Invalid");
                    success = false;
                }
            }
            if (success)
                return RedirectToAction(nameof(Index));
            else
                return View(nameof(CreateEdit), feature);
        }

        private bool IsFeatureNameValid(Feature feature)
        {
            var regexMatch = Regex.Match(feature.ControllerName, @"(\W)");
            return !regexMatch.Success;
        }

    }
}

BulkyBook.Web/Areas/Admin/Views/Feature/CreateEdit.cshtml
@model Feature

<div class="row pb-3">

    <form method="post" asp-controller="Feature" asp-action="AddUpdate">

        <div class="row p-3">
            <input type="hidden" asp-for="Id" />
            <span asp-validation-for="ControllerName" class="text-danger"></span>
            <label asp-for="ControllerName"></label>
            <input asp-for="ControllerName" />
        </div>

        <div class="row p-3">
            <button type="submit" class="btn btn-primary col-6">
                @if (Model.Id == 0)
                {
                    <i>Add</i>
                }
                else
                {
                    <i>Update</i>
                }
            </button>

            <a class="btn btn-primary col-6" asp-action="Index">Back</a>
        </div>

    </form>

</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

BulkyBook.Web/Areas/Admin/Views/Feature/Index.cshtml
@model IEnumerable<Feature>

<div class="container p-3">
    <div class="row">
        <div class="col-6 me-auto">
            <a class="btn btn-primary" asp-controller="Feature" asp-action="CreateEdit">Create Feature</a>
        </div>
    </div>

    <div class="row">
        <table class="table tabel-bordered table-striped text-center" width="100%">

            <thead>
                <tr class="text-nowrap">
                    <th>Controller Name</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var category in Model)
                {
                    <tr>
                        <td>@category.ControllerName</td>
                        <td>
                            <a class="btn secondary" asp-controller="Feature" asp-action="Delete" asp-route-id="@category.Id">
                                Delete
                                <i class="bi bi-trash2-fill"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>

</div>

@section Scripts{
}